name: shipper_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.0
  intl: ^0.19.0
  logger: ^2.3.0
  url_launcher: ^6.3.0
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  freezed_annotation: ^2.4.1
  go_router: ^14.1.4
  flutter_localizations:
    sdk: flutter

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  #  get: ^4.6.5
  get_storage: ^2.1.1
  bloc: ^8.1.3
  flutter_bloc: ^8.1.6

  # Product Specific
  readmore: ^3.0.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  fluttertoast: ^8.2.6
  shimmer: ^3.0.0
  shared_preferences: ^2.2.3
  rxdart: ^0.28.0

  #--------------- ./ PACKAGES END ------------------#

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  freezed: ^2.5.2
  build_runner: ^2.4.11


flutter:
  uses-material-design: true
  generate: true

  #--------------- LOCAL ASSETS ------------------#

  assets:
    - assets/fonts/
    - assets/logos/
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/icons/payment_methods/
    - assets/images/banners/
    - assets/images/content/
    - assets/images/on_boarding_images/
    - assets/images/products/
    - assets/images/reviews/
    #    - assets/images/animations/
    - assets/images/animations/sammy-line-come-back-later.png
    - assets/images/animations/sammy-line-man-receives-a-mail.png
    - assets/images/animations/sammy-line-sale.png
    - assets/images/animations/sammy-line-success.png
    - assets/images/animations/sammy-line-travel-backpack-with-passport-and-air-ticket.gif
    - assets/images/animations/sammy-line-workout.gif

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

    #--------------- CONFIG ------------------#

flutter_gen:
  output: lib/resources/generated
  line_length: 160
  null_safety: true
  package_parameter_enabled: true
  integrations:
    flutter_svg: true
    lottie: true
  assets:
    enabled: true
#    exclude:
#      - assets/images/animations/

# Run the following command to generate the files:

#  fluttergen -h
#  fluttergen -c /flutter_gen.yaml